_BASE_: config.yaml
DATASETS:
  TRAIN: ("cityscapes7_train",)
  TEST:  ("cityscapes19_val",)
MODEL:
  META_ARCHITECTURE: "S2Corr"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    NAME: "S2_CorrHead"
    IN_FEATURES: ["res2", "res3", "res4"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 19
    TRAIN_CLASS_JSON: "datasets/cityscapes_seen_7.json"
    TEST_CLASS_JSON:  "datasets/cityscapes_19.json"
    CLIP_PRETRAINED: "EVA02-CLIP-L-14-336"
    PROMPT_DEPTH: 0
    PROMPT_LENGTH: 0
    TEXT_GUIDANCE_DIM: 768
    TEXT_GUIDANCE_PROJ_DIM: 128
    APPEARANCE_GUIDANCE_DIM: 768
    APPEARANCE_GUIDANCE_PROJ_DIM: 128
    DECODER_DIMS: [64, 32]
    DECODER_GUIDANCE_DIMS: [256, 128]
    DECODER_GUIDANCE_PROJ_DIMS: [32, 16]
    NUM_LAYERS: 1
    NUM_HEADS: 4
    HIDDEN_DIMS: 128
    POOLING_SIZES: [ 1, 1 ]
    FEATURE_RESOLUTION: [32, 32]
    GAMMA: [ 0.6, 0.98 ]
    CHUNK_SIZES: 16
    CLIP_FINETUNE: "attention"
    CACHE_DIR: "/data/zd/TTA_VLM/pretrain/EVA02_CLIP_L_336_psz14_s6B.pt"
  PROMPT_ENSEMBLE_TYPE: "multi_domain"
INPUT:
  MIN_SIZE_TRAIN: (448, 640)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 1344
  MIN_SIZE_TEST: 448
  MAX_SIZE_TEST: 1008
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (448, 448)
  SIZE_DIVISIBILITY: 14
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
SOLVER:
  IMS_PER_BATCH: 4
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.0002
  MAX_ITER: 20000
  BACKBONE_MULTIPLIER: 0.0
  CLIP_MULTIPLIER: 0.01
TEST:
  EVAL_PERIOD: 10000
  SLIDING_WINDOW: True
  SW_KERNEL: 448
  SW_OVERLAP: 0.333
  SW_OUT_RES: [448, 896]
  
